#!/bin/sh
echo "remove gradle.properties, settings.properties to sub chapers."

for var in $(seq 2 9)
do
  if [ -f "chap0$var/gradle.properties" ]; then
    rm chap0$var/gradle.properties
  fi
  if [ -f "chap0$var/settings.gradle" ]; then
    rm chap0$var/settings.gradle
  fi
done

for var in $(seq 10 17)
do
  if [ -f "chap$var/gradle.properties" ]; then
    rm chap$var/gradle.properties
  fi
  if [ -f "chap$var/settings.gradle" ]; then
    rm chap$var/settings.gradle
  fi
done
echo "remove is complete."
