#!/bin/sh
echo "remove gradle.properties, settings.properties to sub chapers."

for var in 2 3 4 5 6 7 8 9
do
  if [ -f "chap0$var/gradle.properties" ]; then
    rm chap0$var/gradle.properties
  fi
  if [ -f "chap0$var/settings.gradle" ]; then
    rm chap0$var/settings.gradle
  fi
done

for var in 10 11 12 13 14 15 16 17
do
  if [ -f "chap$var/gradle.properties" ]; then
    rm chap$var/gradle.properties
  fi
  if [ -f "chap$var/settings.gradle" ]; then
    rm chap$var/settings.gradle
  fi
done
echo "remove is complete."
