DROP TABLE todo IF EXISTS;
CREATE TABLE todo
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    owner       VARCHAR(255)          NOT NULL,
    description VARCHAR(255)          NOT NULL,
    completed   BOOLEAN DEFAULT FALSE NOT NULL
);


DROP TABLE member_role IF EXISTS;
DROP TABLE member IF EXISTS;
CREATE TABLE member
(
    id          BIGINT      NOT NULL,
    username    VARCHAR(50) NOT NULL,
    password    VARCHAR(60) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE member_role
(
    member_id   BIGINT NOT NULL,
    ROLE        VARCHAR(50) NOT NULL,
    FOREIGN KEY (member_id) REFERENCES member
);