DROP TABLE todo IF EXISTS;
CREATE TABLE todo
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    owner       VARCHAR(255)          NOT NULL,
    description VARCHAR(255)          NOT NULL,
    completed   BOOLEAN DEFAULT FALSE NOT NULL
);


DROP TABLE authorities IF EXISTS;
DROP TABLE users IF EXISTS;
CREATE TABLE users
(
    username VARCHAR(50) NOT NULL,
    password VARCHAR(100) NOT NULL,
    enabled  SMALLINT,
    PRIMARY KEY (username)
);

CREATE TABLE authorities
(
    username  VARCHAR(50) NOT NULL,
    authority VARCHAR(50) NOT NULL,
    FOREIGN KEY (username) REFERENCES users
);